name: Docker Image Build

on:
  workflow_dispatch:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create docker container
      run: make docker_build
